onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /switch_control_tb/clk
add wave -noupdate /switch_control_tb/rst
add wave -noupdate /switch_control_tb/SWITCH/currentState
add wave -noupdate /switch_control_tb/SWITCH/selectedInPort
add wave -noupdate /switch_control_tb/SWITCH/routedOutPort
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/routingReq(6) -radix hexadecimal} {/switch_control_tb/routingReq(5) -radix hexadecimal} {/switch_control_tb/routingReq(4) -radix hexadecimal} {/switch_control_tb/routingReq(3) -radix hexadecimal} {/switch_control_tb/routingReq(2) -radix hexadecimal} {/switch_control_tb/routingReq(1) -radix hexadecimal} {/switch_control_tb/routingReq(0) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/routingReq(6) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(5) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(4) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(3) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(2) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(1) {-height 15 -radix hexadecimal} /switch_control_tb/routingReq(0) {-height 15 -radix hexadecimal}} /switch_control_tb/routingReq
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/routingAck(6) -radix hexadecimal} {/switch_control_tb/routingAck(5) -radix hexadecimal} {/switch_control_tb/routingAck(4) -radix hexadecimal} {/switch_control_tb/routingAck(3) -radix hexadecimal} {/switch_control_tb/routingAck(2) -radix hexadecimal} {/switch_control_tb/routingAck(1) -radix hexadecimal} {/switch_control_tb/routingAck(0) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/routingAck(6) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(5) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(4) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(3) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(2) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(1) {-height 15 -radix hexadecimal} /switch_control_tb/routingAck(0) {-height 15 -radix hexadecimal}} /switch_control_tb/routingAck
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/data(0) -radix hexadecimal} {/switch_control_tb/data(1) -radix hexadecimal} {/switch_control_tb/data(2) -radix hexadecimal} {/switch_control_tb/data(3) -radix hexadecimal} {/switch_control_tb/data(4) -radix hexadecimal} {/switch_control_tb/data(5) -radix hexadecimal} {/switch_control_tb/data(6) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/data(0) {-height 15 -radix hexadecimal} /switch_control_tb/data(1) {-height 15 -radix hexadecimal} /switch_control_tb/data(2) {-height 15 -radix hexadecimal} /switch_control_tb/data(3) {-height 15 -radix hexadecimal} /switch_control_tb/data(4) {-height 15 -radix hexadecimal} /switch_control_tb/data(5) {-height 15 -radix hexadecimal} /switch_control_tb/data(6) {-height 15 -radix hexadecimal}} /switch_control_tb/data
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/sending(6) -radix hexadecimal} {/switch_control_tb/sending(5) -radix hexadecimal} {/switch_control_tb/sending(4) -radix hexadecimal} {/switch_control_tb/sending(3) -radix hexadecimal} {/switch_control_tb/sending(2) -radix hexadecimal} {/switch_control_tb/sending(1) -radix hexadecimal} {/switch_control_tb/sending(0) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/sending(6) {-height 15 -radix hexadecimal} /switch_control_tb/sending(5) {-height 15 -radix hexadecimal} /switch_control_tb/sending(4) {-height 15 -radix hexadecimal} /switch_control_tb/sending(3) {-height 15 -radix hexadecimal} /switch_control_tb/sending(2) {-height 15 -radix hexadecimal} /switch_control_tb/sending(1) {-height 15 -radix hexadecimal} /switch_control_tb/sending(0) {-height 15 -radix hexadecimal}} /switch_control_tb/sending
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/SWITCH/freePorts(6) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(5) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(4) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(3) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(2) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(1) -radix hexadecimal} {/switch_control_tb/SWITCH/freePorts(0) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/SWITCH/freePorts(6) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(5) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(4) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(3) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(2) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(1) {-height 15 -radix hexadecimal} /switch_control_tb/SWITCH/freePorts(0) {-height 15 -radix hexadecimal}} /switch_control_tb/SWITCH/freePorts
add wave -noupdate -radix hexadecimal -childformat {{/switch_control_tb/table(0) -radix hexadecimal} {/switch_control_tb/table(1) -radix hexadecimal} {/switch_control_tb/table(2) -radix hexadecimal} {/switch_control_tb/table(3) -radix hexadecimal} {/switch_control_tb/table(4) -radix hexadecimal} {/switch_control_tb/table(5) -radix hexadecimal} {/switch_control_tb/table(6) -radix hexadecimal}} -expand -subitemconfig {/switch_control_tb/table(0) {-height 15 -radix hexadecimal} /switch_control_tb/table(1) {-height 15 -radix hexadecimal} /switch_control_tb/table(2) {-height 15 -radix hexadecimal} /switch_control_tb/table(3) {-height 15 -radix hexadecimal} /switch_control_tb/table(4) {-height 15 -radix hexadecimal} /switch_control_tb/table(5) {-height 15 -radix hexadecimal} /switch_control_tb/table(6) {-height 15 -radix hexadecimal}} /switch_control_tb/table
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {35 ns} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {190 ns}
